export const FETCH_CITY_COLLECTION_CUISINE = 'http://localhost:8000/api/v1/city/'
export const FETCH_RESTAURANTS_COLLECTION = 'http://localhost:8000/api/v1/city/collection/'
export const FETCH_RESTAURANTS_DETAILS = 'http://localhost:8000/api/v1/city/restaurant/'
export const FETCH_RESTAURANTS_REVIEW = 'http://localhost:8000/api/v1/city/review/'
export const FETCH_RESTAURANTS_CUISINE = 'http://localhost:8000/api/v1/city/cuisine/'
export const FETCH_SEARCH_RESULTS = 'http://localhost:8000/api/v1/city/search/'